name: Build & Dockerize .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-docker:
    runs-on: ubuntu-latest  # ¡Ahora Linux! Más rápido y barato

    steps:
      - uses: actions/checkout@v4

      # 1. Configurar .NET
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      # 2. Restaurar y construir
      - name: Restore & Build
        run: |
          dotnet restore book-manager.sln
          dotnet build book-manager.sln --configuration Release --no-restore

      # 3. Publicar
      - name: Publish
        run: dotnet publish book-manager.sln --configuration Release --output ./publish --no-build
        
